[tool.poetry]
name = "finviz"
version = "1"
description = ""
authors = ["Spok <hackershit@yandex.ru>"]
readme = "README.rst"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = ">=3.9"

[tools.setuptools]
packages = ["finviz"]
